### ISSUE TITLE
Generating *.http files

### ISSUE THREAD

**Issue by staff0rd** [AnWeber/httpyac#119]
This is less a request for this repo and more just asking whether you have pondered generating *.http files.

I have a number of GraphQL apis that I am looking to test out further with httpyac. While the likes of Insomnia/Postman use introspection to hit a GraphQL endpoint, I was thinking I could write a plugin for [graphql code generator](https://www.graphql-code-generator.com/) that during generation also generates httpyac *.http files.

Do you have any thoughts on this or similar?

**Comment by AnWeber** [comment]
The point you raise would definitely be interesting and helpful for many to use, however I haven't gotten around to it in terms of time.
I once thought about offering an import for Postman or OpenApi. Only I am not sure if it is part of the project, because the classes in `httpyac` do not provide any added value for the implementation. I have not implemented a real AST that you can output to file. My plan would be to go with a common format if possible (OpenApi), however I think your plan for GraphQL sounds better. But I'm out of that since I don't maintain GraphQL endpoints myself.
If implementing something along these lines, however, I would consider a conversion in both directions (OpenApi => http => OpenApi) and maybe some extension to the model to better support output to file. Then maybe the implementation of a formatter for *.http files would be possible.

**Comment by staff0rd** [comment]
I have built the [first version of a graphql codegen preset](https://www.npmjs.com/package/httpyac-codegen-graphql) and tested it against the spacex graphql endpoint.

I will extend it in the near future to generate auth and environment settings.

**Comment by AnWeber** [comment]
👍 great:-)

**Comment by staff0rd** [comment]
Now supports auth (via headers), scripts & file variables

https://github.com/staff0rd/httpyac-codegen-graphql/releases/tag/v1.1.0

**Comment by rngtng** [comment]
I've similar thing in mind for postman collections. I've a couple of those and like to export them. Ran some quick test with https://github.com/postmanlabs/postman-collection and it didn't look so bad to get started ;)  Let's see if I can make a proper cli out of that..

**Comment by AnWeber** [comment]
I'm looking for the code to convert my Postman Files on Monday and will post it. But I only built it for my needs at the time. Maybe it will help.

**Comment by AnWeber** [comment]
I close the ticket and add it to my backlog. thx
