### ISSUE TITLE
OMG! Thank you! Httpyac rocks!

### ISSUE THREAD

**Issue by rngtng** [AnWeber/httpyac#129]
Hey @AnWeber. This is not a real  issue, but a **BIG THANK YOU**. You created what I always was dreaming of. I see so many developers being 'locked in' with postman and waste time with point&click or, the other extreme, writing crazy bash/curl/* scripts which are tedious to maintain & understand. Not speaking of version control, open standards etc...

With httpyac I think you hit the right trade-of for being developer focused but with a sane Framework & UX so minimise any overhead - by full scripting flexibility - this encourages automating 'manual' testing at it's best. 

Throughout the day I read the guide and ran already a couple of tests for my scenarios. I'm amazed! I found some minor things here and there, will open dedicated issues for that. THANKS again - Tobi

**Comment by AnWeber** [comment]
Thank you. But the basic idea comes from Huachao Mao (https://github.com/Huachao/vscode-restclient). I was also annoyed by the clicking in Postman and the paywall. Other GUI clients like https://hoppscotch.io/ were also not an option. But unfortunately the development of vscode rest-client has come to a halt and my PR was not merged. Just forking was not an option, because I really wanted to make the project extensible without the permanent need of a maintainer. I don't want to build a dead end. And that's where we are now. I have my desired core features implemented. Implemented CLI und plugin API and checked the whole thing with vscode rest-client bugs if it works.
The project is not yet finished and the finishing touches are missing in many places. I would be happy if a few people find a use for the whole thing and let that flow back into the project. 
Thanks for using. And have fun with it.
