### ISSUE TITLE
Error `requireUncached is not defined` 

### ISSUE THREAD

**Issue by rngtng** [AnWeber/httpyac#136]
When switching a working example from `require(...)` to `requireUncached(...)` I get this error:

```
ReferenceError: requireUncached is not defined
    at Object.action (/Users/.../http/.httpyac.js:31:20)
    at be.trigger (/Users/.../http/node_modules/httpyac/dist/index.js:1:3409)
    at async ie (/Users/.../http/node_modules/httpyac/dist/index.js:1:14784)
    at async $e.trigger (/Users/.../http/node_modules/httpyac/dist/index.js:1:3392)
    at async we (/Users/.../http/node_modules/httpyac/dist/index.js:1:21944)
    at async Va (/Users/.../http/node_modules/httpyac/dist/index.js:115:19709)
    at async Qt (/Users/.../http/node_modules/httpyac/dist/index.js:115:19085)
    at async Object.Ja (/Users/.../http/node_modules/httpyac/dist/index.js:139:3468)
ExecuteHook: httpClient failed
```

Both on CLI and VS-Code plugin,  node version v17.0.1

**Comment by AnWeber** [comment]
`requireUncached` is not needed while using cli. The require cache is only in memory and does not survive a restart of the app. Does not fix the bug, but it should be not your initial problem. 
Try using Javascript Debugger Terminal in VSCode with the httpyac cli. You could debug the .httpyac.js and all requires code.

**Comment by rngtng** [comment]
Right, `requireUncached ` is for CLI  not required and that's what I'm using now when developing the flows. The build-in debugger I never used before, but figured it out now.. cool stuff thx

**Comment by AnWeber** [comment]
I have a hard time providing the `requireUncached` method. I use the correct `Module.createRequire` to load the plugins, because I need to run the packages in the context of package.json. The solution using `vm.runInContext` might work, however I already know that I need/want to switch to `esm` soon. Many important dependencies (chalk, globby, got) already use `esm` and this does not allow clearing the require cache anymore.
Currently, it would be easy to pass the method as an API method, but I would have to mark it as deprecated.

**Comment by rngtng** [comment]
IMHO it's fine to deprecated it. I actually didn't miss it, only tried it as I found it in the guide. I'd rather replace it with the guidance you gave me to use the cli while developing to avoid any caching..

**Comment by AnWeber** [comment]
I think for the ticket there is nothing more to do currently. I will probably throw out `requireUncached` with the next major release.
