### ISSUE TITLE
Problem with global auth token in IntelliJ context

### ISSUE THREAD

**Issue by lazee** [AnWeber/httpyac#14]
Hi,

The IntelliJ HTTP Client plugin keeps client.global env parameters between runs. httpyac doesn't it seems?

We have a setup in our structure where we have a login job setup:

```
### User Login
POST {{auth0_base_url}}/oauth/token
Content-Type: application/json

{
 "client_id": "{{user_auth_client_id}}",
 "client_secret": "{{user_auth_client_secret}}",
 "grant_type": "http://someauth.com/realm",
 "username": "{{user_auth_username}}",
 "password": "{{user_auth_password}}",
 "audience": "an/audience",
 "realm": "Username-Password-Authentication",
 "scope": "openid"
}
> ./login.js
```

with a script like this:

```
client.test('Token retrieved successfully', function () {
  client.assert(response.status === 200, 'Response status is not 200')
  var access = response.body.access_token
  if (access) {
    client.global.set('user_access_token', access)
  }
})
```

This `user_access_token` is stored globally in the IntelliJ plugin in a way where this env parameter is available to requests that are executed later.

So, If I run:

```
### List companies
GET {{my_base_url}}/api/companies
Authorization: Bearer {{user_access_token}}
```

it will work just fine. But If I do this in httpyac, I get the error:

```
...ReferenceError: user_access_token is not defined at Object.userJS...
```

So, my questions are:

* Is this intended behaviour?
* Do you have a suggestions on how I could solve this scenario for httpyac, without breaking this logic within IntelliJ?

**Comment by AnWeber** [comment]
Actually it would have been relatively easy to solve using `@import` and `@ref` but unfortunately I accidentally broke the functionality in the [last release](https://github.com/AnWeber/httpyac/commit/e329188ebc27f80c0d12ca0e3dbbf2fe60bc5097#diff-c5d02890e69906d614bbdc801d6b67eb3967f9b39820ddf89be7fd858d9f49feL71-L118). Sorry. I will fix it again with the next version.

You need to add a [name](https://github.com/AnWeber/httpyac/blob/main/examples/README.md#name) to your login method:
```html
### User Login
# @name login
POST {{auth0_base_url}}/oauth/token
Content-Type: application/json
...
```
Then you just have to [import](https://github.com/AnWeber/httpyac/blob/main/examples/README.md#import) and [reference](https://github.com/AnWeber/httpyac/blob/main/examples/README.md#ref-and-forceref) the login in the other method.
```html
# @import ./login.http

### List companies
# @forceRef login
GET {{my_base_url}}/api/companies
Authorization: Bearer {{user_access_token}}
...
```
Normally this should be compatible with Intellij. But please let me know if this is not the case.

And the error is intended. Because all dynamic variables are stored per file. I want to be able to open two http files (in my vscode extension) that are configured against different environments and the variables should not leak to the other system. With explicit `@import` you disable this protection layer.

**Comment by AnWeber** [comment]
But I'm thinking about bypassing it for the Intellij scripts in general, since explicitly a global.set is called. I will have a look at it.

**Comment by AnWeber** [comment]
It is now possible to run it without modifying the *.http files, but --interactive must be added to the httpyac command to prevent the program from terminating. If the calls are not in one file, they can be loaded at the same time using glob pattern (**/*.http).
This procedure is necessary, because I don't want to persist the variables on the hard disk, because they could contain passwords or more.

**Comment by lazee** [comment]
Thank you so much for your help! The `@name`/`@forceRef` works in VSCode. And it doesn't break IntelliJ it seems. I can live with this solution. 
 
The last --interactive fix I guess cannot be transferred to the VSC plugin?

**Comment by lazee** [comment]
AND: Thank you for sharing this tool with us! It is so cool and a great timesaver... :)

**Comment by AnWeber** [comment]
the --interactive fix is not needed in VS Code plugin. The intellij variables are cached as long as my extension is active and therefore it should just work there now. Prerequisite is the version 2.5.0
