### ISSUE TITLE
How to test plugins?

### ISSUE THREAD

**Issue by rngtng** [AnWeber/httpyac#145]
Yet another question ;)  I just created my first tiny httpyac plugin \o/. Same time its my first JS project ever, too.

https://github.com/rngtng/httpyac-plugin-yaml-body

No TS and all that jazz (yet) - but I wanted at least to test it before releasing. I got the test framework up and running, but I wonder how can I ensure `cli.execute` to load the plugin for testing? I thought of a deeper layer than the `cli` which could be evoked and load the plugin? Any ideas?

If you have the time pls check https://github.com/rngtng/httpyac-plugin-yaml-body/blob/main/test/index.test.js#L12-L17.  Thanks

**Comment by rngtng** [comment]
Ah I think I found it. The `*.http` file needs a global script:
```
{{
  const plugin = require("../src/index");
  plugin(httpFile);
}}
...
```

**Comment by AnWeber** [comment]
It would work since my PluginAPI and the HttpFile both have the property `hooks`, but doesn't feel right. However, I would not test this at all. Instead, I would export the method and test it. For me, this would be a unit test and the test via CLI would be an integration test.

onRequestHook.js
```js
module.exports = (request, context) => {
    var { headers, body } = request;
    if (!isYamlContent(headers['content-type']) && isYaml(body)) {
      response.headers["content-type"] = "application/json";
      request.body = JSON.stringify(YAML.parse(body));
    }
  }
```
index.js
```js
api.hooks.onRequest.addHook("signRequest", require('./onRequestHook');
```
For checking if the interface is still implemented correctly, I would leave exactly Typescript. By implementing Typescript you will also find that the body can also be a buffer or array and your script will generate an error in other use cases ([`< ./icon.pdf`](https://httpyac.github.io/guide/request.html#imported-request-body), [multipart/form-data requests](https://httpyac.github.io/guide/request.html#multipart-form-data)). To get automatic updates from httpyac, you can then enable [Dependabot in Github](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/configuring-dependabot-security-updates). And automatic delivery in npm would be the [following](https://github.com/AnWeber/httpyac/blob/main/.github/workflows/publish.yml).

**Comment by AnWeber** [comment]
And reading the header using `headers['...']` is problematic. I don't change the casing of the headers. If someone uses `Content-Type` it doesn't work properly. Use `api.utils.getHeader('...')` instead.

**Comment by rngtng** [comment]
thanks the feedback. just figured it on my own, but will update to your suggestions.

**Comment by AnWeber** [comment]
I think it's a great idea, by the way. And it should all be just suggestions. I can't help myself when I see something to improve:-)

**Comment by rngtng** [comment]
Updated: https://github.com/rngtng/httpyac-plugin-yaml-body/pull/2

I kept one high-level integration test, moved the edge cases to unit test. I c&p you `getHeader` to stay independent as much of the inner httpyac implementation. Next setting up pipeline and publish npm :P

**Comment by AnWeber** [comment]
I was wondering the same thing, if I would copy the method or just use it. I would have copied it too.

**Comment by rngtng** [comment]
And there it is https://www.npmjs.com/package/httpyac-plugin-yaml-body!!! wuhu :)

**Comment by rngtng** [comment]
closing this issues. guess my plugin answers the question. Sure the API could be improved, but no urgency.

**Comment by staff0rd** [comment]
Very cool! I will give it a try

**Comment by rngtng** [comment]
Ah stupid me - *now* I found the right solution. The one earlier was a hack and didn't work for any parsing related hooks. BUT this works: Create at `.httpyac.js` in test folder and init plugin with:

```js
const plugin = require("..path to plugin index...");

module.exports = {
  configureHooks: function (api) {
    plugin(api);
  }
}
```

**Comment by AnWeber** [comment]
I don't think that's quite straight yet either. Better would be to create a `package.json` and import the dependency there using `"httpyac-plugin-yaml-body": "../"`. Then it would also be tested if the name is recognized correctly. I haven't gotten around to trying it out yet, though.

**Comment by rngtng** [comment]
hm but at least the interface of `api` is now the same!? In a certain way I like the explicit nature of loading the plugin this way..

**Comment by AnWeber** [comment]
Yes. I is the same api. It was also more a test to see if the idea works. I don`t really like the extra `npm i` either. I close the PR.
