### ISSUE TITLE
Request: Ability to complete OIDC flows when working in a Dev Container

### ISSUE THREAD

**Issue by jrussellsmyth** [AnWeber/httpyac#202]
The quite useful capability of performing OIDC login flows as part of a request is non-functional when run using VSCode DevContainers - all other functionality works as expected, performing requests from within the container.

The need would be for the extension to configure port forwarding for the callback server and launch the system browser in the HOST instead of inside the container, to complete the request.

I do not know off hand if this is even possible, but it would DRAMATICALLY improve the usability of the tool.

My current workaround is to manually forward port 3000 (has to be forwarded to the same port as in the container or this does not work) and copy/paste the auth url from the VSCode popup. Not really something that you want to do a lot.

**Comment by AnWeber** [comment]
For development I would recommend using [vscode-httpyac](https://github.com/AnWeber/vscode-httpyac). 
I actually always use the client credentials flow in Docker containers for testing. This does not require any manual input and is therefore best suited for automated testing. Password Flow would also work. However, this means that you should set up a separate client on the OAuth server.
If this is not possible, one would have to trick, since a direct call of applications on the host is not possible. You would have to get [open](https://github.com/sindresorhus/open) to use curl when calling the auth url (xdg-open is used with [$BROWSER](https://askubuntu.com/questions/18418/how-can-i-set-which-application-is-launched-by-xdg-open)). Then you could redirect it to a local ExpressJS server, which can then use `open` to open the url on the host as well. You could also enable port forwarding via expressjs. But this is very fiddly and I then wonder what advantage there is to running httpyac in a devcontainer, since a setup must also be performed on the client.

**Comment by LePau** [comment]
@jrussellsmyth @AnWeber I think the following link might be a solution.  I'm currently setting things up, but did a prelim test by installing xdg-utils in my dev container, setting up an `authorization_code` request in httpyac, and it seemed to work OK so far.

https://github.com/microsoft/vscode-remote-release/issues/3540#issuecomment-1283885029
