### ISSUE TITLE
Problem with transitive request references not being resolved

### ISSUE THREAD

**Issue by wusawo** [AnWeber/httpyac#205]
Hi @AnWeber,
first of all, thanks for httpyac. I really appreciate your work.

I noticed a problem with nested request references where each request resides in a dedicated .http file.

### Starting point
File: a.http
```
# @name getHttpbinA
GET https://httpbin.org/get?source=getHttpbinA HTTP/1.1
X-Foo: barA
```

File: b.http
```
# @import ./a.http

###
# @name getHttpbinB
# @ref getHttpbinA
GET https://httpbin.org/get?source=getHttpbinB HTTP/1.1
X-Foo: barB-{{getHttpbinA.headers["X-Foo"]}}
```

File: c.http
```
# @import ./b.http

###
# @name getHttpbinC
# @ref getHttpbinB
GET https://httpbin.org/get?source=getHttpbinC HTTP/1.1
X-Foo: barC-{{getHttpbinB.headers["X-Foo"]}}
```

### Observation 1: 
Calling `getHttpbinC` in vscode yields `ReferenceError - getHttpbinA is not defined`
The direct dependency `getHttpbinB` was resolved correctly; whereas `getHttpbinA` was not.
The httpyac variable view shows
![image](https://user-images.githubusercontent.com/100028522/154802608-97a2d6cb-8269-4dc6-8ee8-293e5f572f63.png)

### Observation 2:
Calling `getHttpbinB` in vscode works as expected. 
The httpyac variable view shows
![image](https://user-images.githubusercontent.com/100028522/154802692-6d0b1ec8-ed5b-4462-9565-7fd83fe7d3ad.png)

Calling `getHttpbinC` then without clearing the response history works.
However, the httpyac variable view misses `getHttpbinA`
![image](https://user-images.githubusercontent.com/100028522/154802826-968ed976-472b-4da1-87f1-528404f013a8.png)

### Observation 3:
If all 3 requests reside in a single .http file calling `getHttpbinC` works.
Also, the httpyac variable view is complete
![image](https://user-images.githubusercontent.com/100028522/154803024-557a5bc4-cf12-4611-8689-2dd50ba8acb1.png)

**Comment by AnWeber** [comment]
@wusawo Thanks for the issue. I can reproduce the error. If `b.http` uses `@import` in same region, it would work (workaround). 

```
# @import ./a.http
# @name getHttpbinB
# @ref getHttpbinA
GET https://httpbin.org/get?source=getHttpbinB HTTP/1.1
X-Foo: barB-{{getHttpbinA.headers["X-Foo"]}}
```
The global import in `b.http` seems to generate the problem. I will debug and fix it later.

**Comment by AnWeber** [comment]
The cause was a bad attempt to avoid an infinite loop when searching for the references. When executing `@ref b.http` all loaded imports are removed I thought I only remove the import for `c.http`. But since the import in b.http is global, it was already there and thus also removed and was missing afterwards.  
I have now adjusted the search algorithm so that it is no longer a recursive function, but only searches the imports for the current file.
The fix will be delivered with the next version. But I will need a few more days for this, because I am currently playing with the customization of the extension for support of [vscode.dev](vscode.dev).

**Comment by wusawo** [comment]
Thank you for the quick reply and fix. Looking forward to the next release 🙂

**Comment by wusawo** [comment]
@AnWeber, while using your proposed workaround, I noticed another issue. Maybe your fix already covers this one but I am not sure. 

Here is what I changed: I made request `getHttpbinB` (file b.http) to apply a dynamic value (uuid) on each request
```
# @import ./a.http
# @name getHttpbinB
# @ref getHttpbinA
GET https://httpbin.org/get?source=getHttpbinB HTTP/1.1
X-Foo: barB-{{$uuid}}
```
Also, I forced to execute the reference upon sending `getHttpbinC` in c.http
```
# @import ./b.http

###
# @name getHttpbinC
# @forceRef getHttpbinB
GET https://httpbin.org/get?source=getHttpbinC HTTP/1.1
X-Foo: barC-{{getHttpbinB.headers["X-Foo"]}}
```

Result
- The first time I am executing `getHttpbinC` the response variable getHttpbinB contains the expected value of the X-Foo header
- In subsequent calls however (w/o resetting environment), the response variable getHttpbinB contains the value of the previous run. This can be seen when looking at the generated uuid.
  ![image](https://user-images.githubusercontent.com/100028522/155163634-601a7010-b6f5-4c97-a589-bea7d6c4412e.png)

**Comment by AnWeber** [comment]
I love how detailed you describe your Issues. Will check it out.

**Comment by wusawo** [comment]
And I love using httpyac.

**Comment by AnWeber** [comment]
@wusawo hahaha  I hope it stays that way, as many bugs as you find:-) 👍🏻 
This is a bug in the handling of the variables and the useRegionScopedVariables setting. I should not have implemented this request. I didn't notice this before, because I usually don't expect dynamic data from the same request. Changed data was not imported using `@forceRef`.

**Comment by AnWeber** [comment]
@wusawo I have provided the update to v5 with the fixes in it
