### ISSUE TITLE
value substitution does not work for variables

### ISSUE THREAD

**Issue by nimatrueway** [AnWeber/httpyac#216]
Sample:

```
@date={{$datetime iso8601 1 s}}

###

GET https://reqbin.com/echo/get/json?date={{date}}
```

Result:

```
`GET https://reqbin.com/echo/get/json?date={{$datetime%20iso8601%201%20s}}`  
  
`HTTP/1.1 200 - OK`
```

**Comment by nimatrueway** [comment]
By the way thanks a lot for this fantastic tool, It's DI handiest rest/grpc client tool I've ever come across! ❤️

**Comment by AnWeber** [comment]
The cause was a processing of the VariableReplacer in the wrong order. First the URL was searched for the occurrence of rest client variables and then the variables were replaced. Well, stupid. The simple fix is to adjust the order. 
It is still possible using javascript to reinsert a `{{$datetime}}` that would not be replaced. However, I think I'll ignore this one, since it will probably never be used.

**Comment by nimatrueway** [comment]
Thanks for the quick fix and explanations 🙏
