### ISSUE TITLE
Support PKCE for authorization code flow

### ISSUE THREAD

**Issue by thzink** [AnWeber/httpyac#219]
PKCE is an extension to the authorization code flow to prevent authorization codes from being intercepted by a third party before being redeemed at the token endpoint. The extension is specified here:

https://datatracker.ietf.org/doc/html/rfc7636

This is a very common feature, which is also part of the successor specification OAuth 2.1. Therefore it seems to make sense if httpyac would support it.

Identity providers can enforce the use of PKCE, which means that httpyac currently cannot be used with these identity providers.

I have created a patch (based on branch "main") with the necessary code changes. Since I cannot commit it to the repository I provide the patch file [pkce.zip](https://github.com/AnWeber/httpyac/files/8207780/pkce.zip) as attachment of this issue.

The patch adds an additional flag `{{prefix}}_pkce` to the Open ID Configuration.  Example:

```
@local_authorizationEndpoint = http://127.0.0.1:8080/auth/realms/local/protocol/openid-connect/auth
@local_tokenEndpoint = http://127.0.0.1:8080/auth/realms/local/protocol/openid-connect/token
@local_clientId = httpyac
@local_redirectUri = http://localhost:4200
@local_scope = openid profile

# Enable PKCE for this client
@local_pkce = true

GET /secured_service HTTP/1.1
Authorization: openid client_credentials local
```

Once enabled, the additional parameters `code_challenge` and `code_verifier` (specified by PKCE) are sent with the authorization request and token request respectively. I could test the patch in my local environment successfully using Keycloak as identity provider.

I would be really happy if PKCE support will be added to httpyac in future.

**Comment by AnWeber** [comment]
I will look at the change. I wanted to implement PKCE once before, but I didn't have a chance to test it. Let's see.

**Comment by thomas-zink** [comment]
Gladly, if it's no trouble.

**Comment by AnWeber** [comment]
would be even easier for me. I have not worked with git patch files yet. I will do it anyway, but with PR you also have the automatic test and everything.
I'm just not sure yet if I will remove dependency pkce_challenge in the aftermath. I have already coded a [similar method](https://github.com/AnWeber/httpyac/blob/e028b2b2cbc2ee45e325cf0c40a43fb64db3e754/src/utils/stringUtils.ts#L29-L36).

**Comment by thomas-zink** [comment]
Some notes on further improvements:

__No support for code_challenge_method=plain__

PKCE defines two different transformations for the code verifier: "plain" and "S256" (see https://datatracker.ietf.org/doc/html/rfc7636#section-4.2). The plain transformation (if you really want to call it a "transformation") can be used only if the client is not capable of computing a SHA 256 hash. Since a node app will always be able to compute a SHA 256, the plain case is ignored.

__Enabled or disabled by default__

[The spec states](https://datatracker.ietf.org/doc/html/rfc7636#section-5):

> [...] client implementations of this specification do not need to know if the server has implemented this specification or not and SHOULD send the additional parameters as defined in [Section 4](https://datatracker.ietf.org/doc/html/rfc7636#section-4) to all servers.

Consequently, PKCE could be turned on by default. On the other side, I'm not sure if there could be identity providers rejecting PKCE-enabled clients simply because of the unexpected code challenge/verifier parameters. In order not to break existing installations it might be wise to keep it off by default.

**Comment by AnWeber** [comment]
I have now released PKCE support with v5.2.0. Please test it again with your OAuth2 server if it still fits for you after my changes. Thanks for the pull request.

**Comment by thzink** [comment]
It's working for me. Thanks for adding this change so quickly.

**Comment by AnWeber** [comment]
You are welcome:-)
