### ISSUE TITLE
Test output order incorrect when using loops

### ISSUE THREAD

**Issue by gerukin** [AnWeber/httpyac#243]
Given this test file:
```
{{
  module.exports = require('../../tests/')

  const body = { id: '{{$guid}}', hello: 'world' }
  module.exports._testBody = body
  module.exports._propertiesToRemove = Object.keys(body)
}}

### Test 1
https://httpbin.org/status/200

{{
  tests.status.is(test, response, { val: 200 })
}}

### Test 2
POST https://httpbin.org/post
Content-Type: application/json

{{_testBody}}

{{
  tests.status.is(test, response, { val: 400 })
}}

### Test 3 (bug)
# @loop for property of _propertiesToRemove
{{
  const body = { ..._testBody }
  delete body[property]
  module.exports._bodyWithPropertyRemoved = body
}}
POST https://httpbin.org/post
Content-Type: application/json

{{_bodyWithPropertyRemoved}}

{{
  tests.status.is(test, response, { val: 200 })
}}
```

We get this result:
<img width="490" alt="screenshot" src="https://user-images.githubusercontent.com/36127103/161500555-16b3ef42-0ca6-4e3c-aebe-a104227c837f.png">

Note: using version `5.3.0`

**Comment by AnWeber** [comment]
There is a general problem, how the loopMetaDataHandler currently works. With the commit from just now, it already works to some extent, but I can still figure out error sources. This currently requires special logic and also duplicates code from other hooks. I'll have to clean that up. That's why for example #242 doesn't work, because I forgot to add the necessary code to loopMetaDataHandler.

**Comment by AnWeber** [comment]
By changing how the loopMetaDataHandler works in 7de59855a6025e70eb274981e76e0315aed9eaee, the error was corrected. This allowed me to remove some hacks. The logs should now be correct when executed. Thanks.

**Comment by gerukin** [comment]
Works fine now, thanks!
