### ISSUE TITLE
Add falsy-allowing variable replace

### ISSUE THREAD

**Issue by fredrikhr** [AnWeber/httpyac#268]
There are several cases I have encountered that the replaced text from a variable replacer ended up being falsy (e.g. empty string). Because the output of the variable replacer is falsy, httpyac uses the original template string verbatim, instead of replacing it with an empty string.

Common scenarios where I have encountered this is when prompting for user input for e.g. a query parameter that legally accepts empty strings.

I do however realize that there might be other issues with simply replacing falsy values. Maybe we could add a new syntax for falsy-forgiving replacement? E.g. `{{? falsyExpression }}`. And maybe just modifying the javascript expression replacer is already good enough.

**Comment by AnWeber** [comment]
That an empty string was not allowed here is an error. I think it should work correctly without new syntax. Only the substitution of boolean would currently not be [converted correctly as string](https://github.com/AnWeber/httpyac/blob/main/src/utils/stringUtils.ts#L39), but rather only because I would not know which value to use (true vs 1 vs yes).

**Comment by fredrikhr** [comment]
Great! Okay, then we can close this :+1:
