### ISSUE TITLE
httpyac not recognizing http-client.env.json files on WSL

### ISSUE THREAD

**Issue by garywoodfine** [AnWeber/httpyac#282]
I've run into an issue that only seems to happen on Windows Subsystem for Linux (WSL).  Which is quite irritating and I'm hoping you could end my frustration :-)

I have a project set up where I have my project set up as follows:
```shell
.
├── Asserts
│   ├── Should_be_200_OK.js
│   └── Should_be_201.js
├── http-client.env.json
├── .httpyac.json
├── Integration.Tests.csproj
└── Tests
    └── post-tests.http
```

When I run the command  the command below on Linux or Mac it works as expected and is great

`httpyac ./tests/Integration.Tests/Tests/*  --all  -e dev --json`  or `httpyac ./tests/Integration.Tests/Tests/*  --all  -e dev -o short`

However, when it comes to Windows and even though I am using Windows Subsystem for Linux (ubuntu)  the command fails 

`ReferenceError: host is not defined`   which seems to indicate HttpYac can't find the `http-client.env.json` where all environment variables have been defined.

This only seems to happen on WSL though!

Feel free to check out the sample project https://github.com/Geek-I-Am/post-service

The really annoying things is when I run the tests in Rider on Windows they work as expected!  So I know the tests work. and if I run the tests on any other OS using the HttpYac they work.  It's only Windows that is the issue.

**Comment by AnWeber** [comment]
I have made the following adjustments, and the Intellij file is used correctly (see [fork](https://github.com/AnWeber/post-service))

```json
{
  "dev": {
    "host": "http://httpbin.org",
    "article_id": "f304d539-4bb8-4026-a5e7-3929990e09f3"
  }
}
```
```
GET {{host}}/get?{{article_id}}
Accept: application/json
```
<img width="473" alt="image" src="https://user-images.githubusercontent.com/13434739/168438049-020dd6ad-e276-40bd-b1e9-d80b52615eb5.png">

Can the error possibly be related to the resolution of localhost in the WSL 2 environment. NodeJS always uses 127.0.0.1 instead of localhost, I haven't found the reason yet. [WSL2 has a virtualized network adapter}(https://docs.microsoft.com/en-us/windows/wsl/networking#accessing-a-wsl-2-distribution-from-your-local-area-network-lan) and there might be problems with resolving the address. I always avoid access from Linux to Windows IP addresses or the other direction for that reason, but this [stackoverflow post](https://stackoverflow.com/questions/64763147/access-a-localhost-running-in-windows-from-inside-wsl2) would provide a solution to the problem..
If not, the command used and the error message might be interesting

**Comment by garywoodfine** [comment]
@AnWeber it is a really peculiar problem.

What we have found that works is WSL we need to create a `dev.env` file  with our settings
```sh
   host =  http://localhost:5000
   article_id = 314de43e-0039-441d-8da5-c5edd2859ded
```

The tests will run. However, this means we will need to maintain two copies of the settings files one for Windows developers and one for Linux/Mac developers.

So I'm not sure if this relates to WSL not being able to map to Localhost, because we use localhost in the `dev.env`

It seems to be related to WSL in some way ignoring or not picking up the `http-client.env.json`  which is odd because if you run the tests in httpyac on Mac/Linux they run fine without the `dev.env` file

**Comment by AnWeber** [comment]
> So I'm not sure if this relates to WSL not being able to map to Localhost, because we use localhost in the dev.env

probably not. With my example with httpbin I also wanted to show that it works correctly for me under WSL (Ubuntu 22.04 and Node v16.13.2).
Another idea would be that there are difficulties to actually read the file (CRLF/ LF issue or similar). This would be found out by [activating `--verbose'](https://github.com/AnWeber/httpyac/blob/main/src/plugins/intellij/intellijVariableProvider.ts#L79-L80).
```
httpyac **/*.http -e dev --verbose
```
If that doesn't help, I would briefly recommend just [debugging it once in WSL. I can help there](https://github.com/AnWeber/httpyac/blob/main/.github/CONTRIBUTING.md#debug). The solution with the dev.env file is not good either. I will additionally add a few log additions to possibly better isolate the problem with the next version.

**Comment by garywoodfine** [comment]
I'll try the debugging option on Monday, try get as much information as I can.

**Comment by AnWeber** [comment]
Here are the complete instructions
1. Install [VSCode Remote Development](https://code.visualstudio.com/docs/remote/wsl-tutorial)
2. ```git clone https://github.com/AnWeber/httpyac.git```
3. ```cd httpyac && npm i && npm link && npm run compile && code .```
4. in VSCode add Breakpoint in [intellijVariableProvider.ts](https://github.com/AnWeber/httpyac/blob/main/src/plugins/intellij/intellijVariableProvider.ts#L27)
5. open [Javascript Debug Terminal](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_javascript-debug-terminal), navigate to your project and execute ```httpyac **/*.http -e dev```

I changed the necessary line in the last commit so that it is identical to [dotenvVariableProvider](https://github.com/AnWeber/httpyac/blob/main/src/plugins/dotenv/dotenvVariableProvider.ts#L64). In the [published version this was different, but should not have changed the behavior](https://github.com/AnWeber/httpyac/blob/5.4.1/src/plugins/intellij/intellijVariableProvider.ts#L21).

**Comment by garywoodfine** [comment]
@AnWeber I have run the verbose option i.e. ` httpyac ./tests/Integration.Tests/Tests/*  --all  -e dev - o short  -v`
and I get the following error message being reported
```shell
/mnt/c/Users/GaryWoodfine/code/Backend/actors/tests/Integration.Tests/http-client.env.json not found
SyntaxError: Unexpected token ﻿ in JSON at position 0
    at JSON.parse (<anonymous>)
    at wu (/home/garywoodfine/.nvm/versions/node/v18.1.0/lib/node_modules/httpyac/dist/index.js:3:37963)
    at async ni (/home/garywoodfine/.nvm/versions/node/v18.1.0/lib/node_modules/httpyac/dist/index.js:3:37479)
    at async Object.ii [as action] (/home/garywoodfine/.nvm/versions/node/v18.1.0/lib/node_modules/httpyac/dist/index.js:3:37790)
{}

```

**Comment by AnWeber** [comment]
I get the error when the file is saved as UTF-8 with BOM. httpyac reads the file as [UTF-8](https://github.com/AnWeber/httpyac/blob/main/src/plugins/intellij/intellijVariableProvider.ts#L77). Is this possibly or some other encoding issue the problem?

**Comment by garywoodfine** [comment]
@AnWeber  That certainly seems to be the problem!

So it appears that when you add a File in Rider on windows, is that it is not added as UTF-8. So I ensured that all files are Encoded to UTF-8 

i.e. File --> File Enconding and Ensuring UTF-8 is selected and if not ensuring the File is converted.
Has solved the problem!

**Comment by AnWeber** [comment]
@garywoodfine Thank you. You are welcome.
