### ISSUE TITLE
Replacement of variables in Objects doesn't work (anymore)

### ISSUE THREAD

**Issue by rngtng** [AnWeber/httpyac#284]
Hey Hey

I came across a bug, which IMHO used to work. When I reference a variable in an object value, it doesn't get replaced (anymore):

```
{{
module.exports = {
  baz: "works"
  foo: {
     bar: "{{baz}}"
  },
}
}}

###
POST https://httpbin.org/anything

{{foo}}
```

Response is
```
...
"data": "{\"bar\":\"{{baz}}\"}",
...
```

But with adding `baz` explizit, the variable gets replaced (because it's known?)
```
###
POST https://httpbin.org/anything

{{baz}}
{{foo}}
```

Results in
```
...
"data": "works\n{\"bar\":\"works\"}",
...
```

My expectation is that even in first case the variable `{{baz}}` is replaced too.

Any idea why that?  Cheers!

**Comment by AnWeber** [comment]
The difference arises in an interesting concatenation of special cases. Using `foo` is a special case because it needs to be automatically converted to a string.  However, since the desired response [consists only of the variable, it is returned directly](https://github.com/AnWeber/httpyac/blob/c118fe6f3fd39f42efd6fede3c8ab51f695374bb/src/utils/parserUtils.ts#L403). I have included this case so that I can pass directly response body from previous request (pdf) and to allow [authentication with grpc](https://github.com/AnWeber/httpyac/blob/c118fe6f3fd39f42efd6fede3c8ab51f695374bb/src/plugins/grpc/grpcClientAction.ts#L51). Already adding a space after the variable would bypass this logic and it would get replaced because foo is replaced by [nameVariableReplacer](https://github.com/AnWeber/httpyac/blob/main/src/plugins/core/replacer/nameVariableReplacer.ts) and baz with [javascriptVariableReplacer](https://github.com/AnWeber/httpyac/blob/main/src/plugins/javascript/javascriptVariableReplacer.ts). NameVariableReplacer is only an optimization to allow Variables without executing scripts in [Untrusted Workspaces](https://code.visualstudio.com/docs/editor/workspace-trust).
Is there a reason why not just directly use template strings from javascript?

```
{{
const baz = 'works';
module.exports = {
  baz,
  foo: {
     bar: `${baz}`
  },
}
}}

###
POST https://httpbin.org/anything

{{foo}}
```

**Comment by rngtng** [comment]
Thanks for your explanation, indeed if I add the space or pass `foo` as query it works:

```
GET https://httpbin.org/anything?foo={{foo}}
```
But i wouldn't if I add it as header, and that's how I actually am using it. Pls check this:

```
GET https://httpbin.org/anything?test={{foo.bar}}
Test: {{foo}}
```

Header value is `Test: [Object object]`.  And for this:

```
GET https://httpbin.org/anything?test={{foo.bar}}
Test: {{foo.bar}}
```

Header value is `Test: {{baz}}`. Is this same problem? Maybe javascriptVariableReplacer is missing for header values?

P.S:

Good idea with the solution in JS, but this doesn't help me, as given example is a simplified version of the actual problem I have ;)  In my actual case the variables emerge out of two environment configs (`.httpyac.js` and `.env.prod`). First contains generic values and resides in version control. The other is ignored in VSC and holds the actual secret used for execution. Example:

.httpyac.js
```
module.exports = {
  environments: {
    prod: {
        client: {
           password: "{{secret}}"
        }
   }
}

```
.env.prod
```
secret=hush
```

```
GET https://httpbin.org/anything
Password: {{client.password}}
```

Results in `Password: {{secret}}`

**Comment by rngtng** [comment]
Ok i found my issue: Similar like the body case, the hash variable as header value doesn't get variable replaced. But wrapping it as array does the trick and is sufficient for my case:

```
GET https://httpbin.org/anything
Test: [{{foo}}]
```
Header value is now `Test: [{"foo":{"bar":"works"}}]`.

Nevertheless I found the different interpretations of the variables depending on query, header or body value confusing. To discuss this, I open this ticket: https://github.com/AnWeber/httpyac/issues/285

Thanks for your support
