### ISSUE TITLE
Global pre-request script clarification / issues

### ISSUE THREAD

**Issue by gerukin** [AnWeber/httpyac#302]
Now that was a bit of a tricky one...

In the docs [it says](https://httpyac.github.io/guide/scripting.html#events):
> If no event is specified for global registration, the script is executed before every request.

I think this may work as you intended but I recently got confused by this statement.

Consider this:
```
{{
	module.exports._someArray = [1, 2]
}}

{{+
	console.log('ah')	// I am logged only once when executing a `loop` below
}}

### Oh nooo, I have no body
# @loop for el of _someArray
{{
	module.exports._testBody = {
		ts: new Date().toISOString()
	}
}}
POST https://httpbin.org/post
Content-Type: application/json

{{ _testBody }}

### But I'm fine, loops are for losers
{{
	module.exports._testBody = {
		ts: new Date().toISOString()
	}
}}
POST https://httpbin.org/post
Content-Type: application/json

{{ _testBody }}
```

So I can see two areas for confusion:
1. looks like the pre-request is actually only evaluated once per run
2. but it seems like it takes over the local pre-request script in every request below... if it's part of a loop

Anyway... I thought it'd be nice to give you some food for thought before going into the WE. 😁 😇

**Comment by AnWeber** [comment]
Yes, I also think that it behaves correctly and I should only write the documentation here more precisely. It boils down to the difference I see between request and region. I but nowhere define the terms.
First to the reason why it works the way it does right now. I wanted to be able to implement the following example using loop.

```
# @name loopItems
GET https://httpbin.org/json
###
# @ref loopItems
# @loop for item of loopItems.slideshow.slides
GET https://httpbin.org/get?title={{item.title}}
```
The special feature is the use of `@ref` before the `@loop`. This is executed only once for the region. Your Global pre reqeust Script behaves in the same way, since it is inserted at the beginning of the region.
The region for me in this example would be the 3 commands `@ref`, `@loop` and `GET ...`. The request however only `GET ...`. For this reason the documentation here is not accurate, because it is not a pre-request script, but more a pre-region script. I would have a pre-request script too, but that would have to be defined with `{+reqeust`. Only because I initially tried to use the same labels as Postman and other tools, the misunderstanding occurs.

**Comment by gerukin** [comment]
Thanks for the clarification! I think your extension is very full featured and it feels nearly impossible to keep track of all possible use cases and combination of options to write the perfect documentation! 🤷‍♂️

There is still something which may not be behaving as intended here though... 🤔

### Structure

This is a file level script (`A`), executed once:
```
{{
	module.exports._someArray = [1, 2]
}}
```

This is a pre-region script (`B`), executed once when running a region (even if there's a loop in it - it runs only once as you described):
```
{{+
	console.log('ah')	// I am logged only once when executing a `loop` below
}}
```

The loop (`L`) will create a separate request per iteration:
```
### Oh nooo, I have no body
# @loop for el of _someArray
```

This script is a pre-request script (`Cx`), which will run before every request in the loop:
```
{{
	module.exports._testBody = {
		ts: new Date().toISOString()
	}
}}
```

This `_testBody` should therefore use the result of the current loop iteration's pre-request script (`Cx`) above (and also be able to access the result of the other scripts (`A` and `B`) which were run only once):
```
POST https://httpbin.org/post
Content-Type: application/json

{{ _testBody }}
```

### Issue

Yet the body is sent completely empty... but if I don't include the loop `L` (or remove the pre-region script `B`), the body is set as expected.

Tests:
* Run as is: body is empty for each request in the loop
* Remove the loop (`L`): body is set properly (just once since there's just one request now)
* Remove the pre-region script (`B`) instead (keep the loop): body is also set properly (for each request in the loop)

Note: I actually have another use case where the body is not set when using a loop and no pre-region script (but this is a complicated test environment which I haven't been able to simplify down to an example yet).

**Comment by AnWeber** [comment]
The cause of the bug was the index manipulation in the loopMetaHandler. This caused the body to no longer be appended to the request.

**Comment by gerukin** [comment]
Thank you! Looks like my issue is gone after the update indeed.
