### ISSUE TITLE
Question: How can I execute an HTTP file programmatically within Node?

### ISSUE THREAD

**Issue by dremekie** [AnWeber/httpyac#316]
I'd like to be able to programmatically do what the CLI is doing. Within node, I'd like to execute one (or more?) http files.

Essentially, I'd like to be able to access something like [this](https://github.com/AnWeber/httpyac/blob/main/src/cli/send/send.ts#L47).

**Comment by AnWeber** [comment]
The following steps would be necessary
- init [IO Provider](https://github.com/AnWeber/httpyac/tree/main/src/io) to access filesystem, logging or user interaction (if needed). e.g [cli](https://github.com/AnWeber/httpyac/blob/main/src/cli/initCliProvider.ts#L22-L142) or [vscode extension](https://github.com/AnWeber/vscode-httpyac/blob/main/src/io/index.ts#L8-L13). Through this layer I tried to encapsulate away accesses to external interfaces to allow for possible special implementations. For example logging to console versus logging to VSCode output. Or use database instead of local filesystem.
- create a [httpFileStore](https://github.com/AnWeber/httpyac/blob/dfec3071d9717b3060c2c7275884b9d7764fee8d/src/store/httpFileStore.ts#L17) to parse files: [cli](https://github.com/AnWeber/httpyac/blob/dfec3071d9717b3060c2c7275884b9d7764fee8d/src/cli/send/send.ts#L176-L180), [vscode-httpyac](https://github.com/AnWeber/vscode-httpyac/blob/main/src/documentStore.ts#L117-L137). 
- use [send](https://github.com/AnWeber/httpyac/blob/dfec3071d9717b3060c2c7275884b9d7764fee8d/src/httpYacApi.ts#L12) method to trigger a request for a httpFile or httpRegion: [cli](https://github.com/AnWeber/httpyac/blob/dfec3071d9717b3060c2c7275884b9d7764fee8d/src/cli/send/send.ts#L64-L71), [vscode-httpyac](https://github.com/AnWeber/vscode-httpyac/blob/78074229158c880f030d36eabcca734e632b9f4a/src/documentStore.ts#L160-L210)

That's roughly the process. If I were you, I would also try setting up [httpyac](https://github.com/AnWeber/httpyac/blob/main/.github/CONTRIBUTING.md), or [vscode-httpyac](https://github.com/AnWeber/vscode-httpyac/blob/main/.github/CONTRIBUTING.md) locally and just debugging through the steps. I would suggest if you can get a few steps ahead with that and then just ask me questions. If you tell me what your idea is, I'll be happy to help you.

**Comment by dremekie** [comment]
Thanks for this. I will give it a go.

**Comment by AnWeber** [comment]
@dremekie Now I wanted to know again myself what to do. The following was my minimal attempt.

```js
const httpyac = require("httpyac");
const fs = require("fs").promises
const {extname, isAbsolute, join, dirname} = require("path");
const {EOL} = require("os");
run()

async function run() {
  initFileProvider();
  const httpFile = await new httpyac.store.HttpFileStore().getOrCreate(`any.http`, async () => Promise.resolve(`
  GET https://httpbin.org/json
  `), 0, {
    workingDir: __dirname,
  });
  await httpyac.send({
    httpFile,
    logResponse: (response) => console.info(response)
  });
}

function initFileProvider() {
  const fileProvider = httpyac.io.fileProvider;
  fileProvider.EOL = EOL;
  fileProvider.isAbsolute = async (fileName) => isAbsolute(fileProvider.toString(fileName));
  fileProvider.dirname = (fileName) => dirname(fileProvider.toString(fileName));
  fileProvider.hasExtension = (fileName, ...extensions) =>
    extensions.indexOf(extname(fileProvider.toString(fileName))) >= 0;
  fileProvider.joinPath = (fileName, path) =>
    join(fileProvider.toString(fileName), path);

  fileProvider.exists = async (fileName) => {
    try {
      return !!(await fs.stat(fileProvider.toString(fileName)));
    } catch (err) {
      return false;
    }
  };
  fileProvider.readdir = async (dirname) =>
    fs.readdir(fileProvider.toString(dirname));
}
```

**Comment by dremekie** [comment]
@AnWeber Thanks very much for this! I will give this a try and report back.

**Comment by dremekie** [comment]
@AnWeber You above snippet worked. Thank you.  One further question:

When using the code snippet, how can we pass variables to the script?

Example: I would like to use the above code snippet to pass `apiKey` to that it can be referenced in the http script (using `{{apiKey}}` ).

**Comment by AnWeber** [comment]
@dremekie Use property variables in the send argument (see https://github.com/AnWeber/httpyac/blob/main/src/models/processorContext.ts#L28 for all args).
