### ISSUE TITLE
httpyac-cli - help inconsistent with usage

### ISSUE THREAD

**Issue by tl3gr4nd** [AnWeber/httpyac#326]
Hello,

From a prompt, I am in a directory containing:
* a HTTP file with my requests (group.http) 
* the httpyac configuration file (httpyac.config.js) where are declared my environments

First, it seems that it is possible to execute the request directly without using the `send` command via `httpyac group.http` even it is not specified in the help screen (`httpyac --help`).

Then, when I try to execute my requests via the `send` command specifying the environment to use, it tells me:
```bash
$ httpyac send --line 11 -e dev group.http
error: missing required argument 'fileName'
```
The help screen for the `send` command specifies that the fileName should be specified **after** the options.

When I tried, it seems to work
```bash
$ httpyac send group.http --line 11 -e dev
```

**Comment by AnWeber** [comment]
I rely completely on [Commander.js](https://github.com/tj/commander.js) for the help text of the CLI output. I actually just pass the [existing options along with the help text](https://github.com/AnWeber/httpyac/blob/main/src/cli/send/send.ts#L17-L43).

> First, it seems that it is possible to execute the request directly without using the send command via httpyac group.http even it is not specified in the help screen (httpyac --help).

Commander.js does not generate automatic output here. It would be possible to override this, but I don't know how other CLI tools do it. Do you have an example for me? Maybe it would make sense to create an issue in Commander.js.

> The help screen for the send command specifies that the fileName should be specified after the options.

This is also generated directly by Commander.js. I think Commander.js assumes a different notation here and therefore outputs the usage this way. Use `httpyac send --line=11 -e=dev group.http` instead of your command without `=`

**Comment by AnWeber** [comment]
The cause is the use of [variadic-option](https://github.com/tj/commander.js#variadic-option) in the [`--env` option](https://github.com/AnWeber/httpyac/blob/main/src/cli/send/send.ts#L22). This causes the filename to be interpreted as an environment option. One solution according to Commander.js is to [change the usage](https://github.com/tj/commander.js/blob/master/docs/options-taking-varying-arguments.md#alternative-put-options-last).
