### ISSUE TITLE
Plugin for JetBrains IDEs

### ISSUE THREAD

**Issue by QuAzI** [AnWeber/httpyac#334]
Do you have any plans to create httpyac plugin for JetBrains IDE's (Rider/WebStorm/DataGrip)? Similar to vscode-httpyac

**Comment by AnWeber** [comment]
@QuAzI Rather not. I looked at it a while ago, but it would take a lot of effort since Jetbrains intentionally doesn't offer the same API (=> [LSP](https://youtrack.jetbrains.com/issue/IDEABKL-7409)). Additionally, there is already an [HTTP implementation in Intellij](https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html) that I am compatible with. You have the option to either just use Intellij's capabilities or just run the CLI tool in the CommandLine. Maybe I change my mind if for [Fleet a plugin API](https://www.jetbrains.com/de-de/fleet/) will be implemented, but until then sorry
