### ISSUE TITLE
Availability of exports from imported files (without @referencing )

### ISSUE THREAD

**Issue by wusawo** [AnWeber/httpyac#358]
Hi @AnWeber, 

one of my requests depends on a variable that might be exported by several different requests. Therefore I cannot work with @referencing a specific request.
I would like to manually call the right requests in the right order to ensure the variable to be set the expected way.
In doing so I noticed that this is already possible when all the requests are in one http-file; however it fails if the exported variable is accessed from another file. Is there a chance to make this work? 

### Reproduction
File: exportsA.http
```
###
# @name getHttpbin1
GET https://httpbin.org/get?source=getHttpbin1 HTTP/1.1
X-Foo: bar1

{{
    exports.theNumber = 24;
    console.info(`getHttpbin1 -> theNumber: ${exports.theNumber}`);
}}


###
# @name getHttpbin2
//# @ref getHttpbin1   <-- WITHOUT @referencing

{{
    console.info(`getHttpbin2 (same file) -> theNumber: ${this.theNumber}`);
}}
GET https://httpbin.org/get?source=getHttpbin2 HTTP/1.1
X-Foo: bar2-{{this.theNumber}}
```

File: exportsB.http
```
# @import ./exportsA.http

###
# @name getHttpbin2
//# @ref getHttpbin1   <-- WITHOUT @referencing

{{
    console.info(`getHttpbin2 (different file) -> theNumber: ${this.theNumber}`);
}}
GET https://httpbin.org/get?source=getHttpbin2 HTTP/1.1
X-Foo: bar2-{{this.theNumber}}

```

### Result
```
INFO: getHttpbin1 -> theNumber: 24
INFO: getHttpbin2 (same file) -> theNumber: 24
INFO: getHttpbin2 (different file) -> theNumber: undefined
```

Regards

**Comment by AnWeber** [comment]
I would solve it using the userSessionStore. UserSessionStore is a cache where I save Cookies, Last Response or the Intellij Global Variables

File: exportsA.http
```
# @name getHttpbin1
GET https://httpbin.org/get?source=getHttpbin1 HTTP/1.1
X-Foo: bar1

{{
    const httpyac = require('httpyac');
    httpyac.store.userSessionStore.setUserSession({
      id: "custom",
      title: "custom store",
      type: "custom",
      details: {
        theNumber: 24
      }
    });
}}
```


File: exportsB.http

```
# @import ./exportsA.http

###
# @name getHttpbin2
{{
    const httpyac = require('httpyac');
    exports.theNumber = httpyac.store.userSessionStore.getUserSession("custom")?.details?.theNumber;
}}
GET https://httpbin.org/get?source=getHttpbin2 HTTP/1.1
X-Foo: bar2-{{theNumber}}
```

The 2nd possibility would be to use [Intellij Script](https://httpyac.github.io/guide/scripting.html#intellij-script) Notation. `client.global.set` set variables in global scope, but it gets only executed after request and use other Javascript API. Script access to variables before the request is at the moment not possible (will change since Intellij Idea 2022.3 changed API and I want to stay compatible). But it would be possible to use variable in the request.

**Comment by wusawo** [comment]
Using IntelliJ Script notation `client.global.set` worked in my scenario as I could use `{{this.theNumber}}` in exportsB.http. Also it seems more easier compared to `userSessionStore` as it [ensures that the underlying `UserSession` instance is available](https://github.com/AnWeber/httpyac/blob/b2abb68071af8da26bef312a560fcabf8ff06ce6/src/plugins/intellij/api/intellijVariables.ts#L14), when writing global variables form multiple different scripts. 

Still I would love to use this capability with httpyac's native script notation.
To better understand your concepts: Is there any reason why variables of a previous run are available on the subsequent run if the subsequent run happens on the same http file; but those variables are not available if the subsequent run happens on a different file. Do you support accessing variables between subsequent runs or is this more or less not intended usage? 
Thanks.

**Comment by AnWeber** [comment]
Initially I just had a global scope. All variables in one dictionary. But tools like Postman work differently. You can define a global variable `url=http://mydomain.de/api/${resource}` in Postman. The variable `resource is set correctly per request variable/ current scope (see https://github.com/httpyac/httpyac.github.io/issues/7). By making this adjustment, [I only load variables that are global, referenced, or defined in the current request.](https://github.com/AnWeber/httpyac/blob/ba1accdb88273838e154d15a0ed37fbd011eb168/src/plugins/core/execute/regionScopedVariablesInterceptor.ts).  However, for the same file, I softened it because I need simplified access to the previous response for daily work, but this [could be deactivated with useRegionScopedVariables](https://github.com/AnWeber/vscode-httpyac/blob/main/package.json#L536). This is the reason for the current behavior.

It might also make sense to enable this for other files as well and switch to the original concept with Global Variables.  Or provide a object, where you can define variables globally. I don't have a firm opinion on this yet, as my use cases are working.

**Comment by AnWeber** [comment]
With the next version there is a special variable `$global` which is available as store for global variables. The cache is managed per environment. This should simplify the solution of this problem

**Comment by wusawo** [comment]
It does. Thanks a lot.
