### ISSUE TITLE
Best way to render .http files for documentation

### ISSUE THREAD

**Issue by rngtng** [AnWeber/httpyac#425]
Hey @AnWeber - is there a common practice on how to render a .http file (with multiple request) for documentation purposes? 
I played around with renaming the file into `.md`  and but the calls in a code block, but then the `@ref` is broken. 

The way how Httpbook gets rendered is nice but same issue here..

any ideas?

**Comment by AnWeber** [comment]
@rngtng  That @ref does not work in httpBook is a bug. I will fix this one. In Markdown files it is working for me ([ref.md](https://github.com/AnWeber/httpyac/files/11093809/ref.md))

I would probably use Markdown, because you make sure it looks good without `httpyac` and you may also have PDF export and such. Also, with vitepress you can create web pages based on it. The best thing to do is just look at the code from httpyac.github.io (https://github.com/httpyac/httpyac.github.io). The whole page is written in Markdown only and that the code examples are outside of Markdown is purely optional and because I find it more helpful that way.

**Comment by rngtng** [comment]
@AnWeber thanks! well, if it's indeed a bug, then we can go with this approach. but nevertheless I see requests in code blocks don't appear as 'test case' in vscode. is this a bug too? On the other hand, not such a big deal..

**Comment by AnWeber** [comment]
@rngtng  add `md` extension to setting [`httpyac.testItemExtensions`](https://github.com/AnWeber/vscode-httpyac/blob/main/package.json#L960). This should also include these tests.

**Comment by rngtng** [comment]
So rendering your file `ref.md` works nice for me, same as exec in vscode but unfortunately not the CLI. This doesn't work for me like with the other `.http` files:

```
httpyac send ref.md
```

**Comment by AnWeber** [comment]
This seems to be the reason: https://github.com/AnWeber/httpyac/blob/main/src/cli/send/send.ts#L189. I will add a new cli arg to override extensions and automatically detect extension if filenname is provided.

**Comment by rngtng** [comment]
Wow. Again thanks a lot for your fast fixes I’ll give it a try later

**Comment by AnWeber** [comment]
`@ref` support in httpbook is also fixed.
