### ISSUE TITLE
How to memorise an $input and not get asked again?

### ISSUE THREAD

**Issue by rngtng** [AnWeber/httpyac#436]
I'm looking for a way to 'remember' the $input value and only get asked if it's not set yet. Example:

I've following config

```
module.exports = {
  defaultHeaders: {
    "Authorization": "Bearer {{token}}",
  },
  environments: {
    "$shared": {
      host: "http://127.0.0.1:8000",
      token: "{{$input Auth Token?}}"
    },
  }
};
```

Now I'd like to be asked for the auth token only initially if `token` is empty. After that the value should be used until I reset env. Is there sth. I can solve this? 

As always: a big THANK YOU already 🍺 🍺 🍺

**Comment by rngtng** [comment]
PS: has it sth todo with lazy variables? Probably `token` is lazy so evaluated everytime the default header is set?

**Comment by AnWeber** [comment]
It is solvable by means of `@ref`. It is not necessary to send a request. It is only expected that a variable is created according to the name of the region.

```
# @name token

@token={{$input Auth Token?}}

###
# @ref token
GET https://httpbin.org/anything
```

However, the setup is unnecessarily difficult because a `# @ref token` must be inserted in all call requests. I extend the logic of `$input` with a modifier `$input-askonce`. This stores the input in the SessionStore and does not ask for it again.

**Comment by rngtng** [comment]
wow thanks again, I owe you one more!
