### ISSUE TITLE
Sensitive Data in Log

### ISSUE THREAD

**Issue by AnWeber** [AnWeber/httpyac#50]
comment of @gerukin in #49

one issue that I'm not sure is addressed by httpyac yet is redaction of confidential / sensitive / secret data in cookies, headers, query strings, req body and so on. If not saving the output, we avoid it there, but it's still potentially an issue with the request... and perhaps even with the response headers and so on. One short term way to deal with this would be to only include the summary info for now while you consider what to do (if anything) for data redaction. Another solution is to include everything, have no built-in redaction mechanism... and leave it to a post script or future adapter too.

**Comment by AnWeber** [comment]
The problem with the sensitive data, exists not only during the output in the JSON summary, but also already during the normal log output on the cli and in vscode. My idea for this was to never output the Authorization Header, however this is not sufficient. Partly custom headers are used for the transfer of data worthy of protection, partly these are transferred in the body. 
My only idea so far was to add a filter that filters out sensitive data in header and body by regex/ name respectively. Only the configuration would be rather difficult to explain.

**Comment by gerukin** [comment]
I think in vscode it's okay to not worry about this in general. Even in ad hoc cli use I also wouldn't worry much. The only real worry I think one should have is when logging data:
1. if you don't save the data anywhere there probably is no liability issue, except,
2. if you access confidential data you are legally / contractually not allowed to (the **server** should not allow those people to query the data to begin with 😇)

When logging though, you probably want to redact sensitive data for security reasons, to avoid leaks, and to allow unprivileged personnel to review the logs (maybe engineers can look at the production logs to debug, but cannot run the CLI in prod themselves because they don't have the credentials). Even if the above isn't a concern, you also may or may not be allowed to keep the data about customers from one region of the world in a server based elsewhere (whereas it might be ok to see it temporarily in your console wherever you are).

### Implementation problem

I don't think httpyac can know what is considered sensitive and what isn't, or even which requests have sensitive data to begin with. Or how much to redact and how much is useful to keep for debugging (even in the same property).

### Suggestion

Given all the above, I would suggest to add a pre-logging lifecycle hook to allow any kind of redaction work (not just to remove / redact stuff even). I don't know where this makes the most sense in httpyac but ideally it would:
* be enabled in the `http` file for each request (and / or globally?)
* allow external file references (to centralize the code) - and ideally more than one, executed sequentially
* expect a returned config object from each file, to transform each property being logged `{ property: val => something(val), /* ... */ }`

Maybe it's like tests (not sure how the hook would be referenced there - each file only affecting this request's logs)?
```
# redact all authentication info from request headers and response cookies
> ./redactors/remove-authentication.js

# redact all customer data
> ./redactors/customer-data/rm-from-comments.js
```

It might be ok to have only one file ref possible here. Maybe it's `# @logging ./redactors/all.js`?

And / or maybe it's [also] globally enabled in `.httpyac.json` with something like:
```json
{
  "hooks": {
    "logging": "./redactors/all.js"
  }
}
```

Then it's up to the user to decide what redaction work makes sense, where in each request, and in which environment(s). Of course this would apply also to vs-code and regular cli use.. but really, I think this likely only matters in prod when logging.

**Comment by AnWeber** [comment]
> I think in vscode it's okay to not worry about this in general.

Exactly in vscode is the place that worries me. I am currently logging the authentication data into the output. This can in principle be read by all extensions. I haven't found a nice solution yet and that's why I still have it on my todo list. 
The idea with the hooks I find interesting. As mentioned before I still want to create a @vue/cli like interface and this should be combined eventually.

**Comment by AnWeber** [comment]
My idea is to explicitly provide a hook before logging. With a custom [httpyac.js](https://github.com/AnWeber/httpyac/blob/cafe2bcd06e1f8a1f69819912ce80b01a5d7e21d/src/models/environmentConfig.ts#L30) file in root dir it is possible to filter sensitive information.

example for .httpyac.js
```
module.exports = {
  configureHooks: function (api) {
    api.hooks.responseLogging.addHook('removeSensitiveData', function (response) {
      if (response.request) {
        delete response.request.headers['authorization'];
      }
    });
  }
}
```
The [hook api](https://github.com/AnWeber/httpyac/blob/cafe2bcd06e1f8a1f69819912ce80b01a5d7e21d/src/models/httpFileHooks.ts#L9) is in principle even more powerful and all my parser and variable provider/replacer logic uses these hooks for processing. The idea for the hooks are based on [webpack/tapable](https://github.com/webpack/tapable). Additionally it is possible to register NPM packages named `httpyac-plugin-...` (see [vue/cli](https://cli.vuejs.org/dev-guide/plugin-dev.html#naming-and-discoverability)). Therefore I would document this now and then publish it (tag next is published if you are curious).

**Comment by AnWeber** [comment]
I have now described the plugin concept in more detail on the new [website](https://httpyac.github.io/). It is not quite finished yet, but it should already be sufficient for simple use cases. With the new hook `responseLogging` you can prefilter the response before output.
