### ISSUE TITLE
Meta option to handle rate limiting (HTTP 429)

### ISSUE THREAD

**Issue by gerukin** [AnWeber/httpyac#52]
Often endpoints are rate limited. Sometimes by endpoint and sometimes by API key (or both). Usually by _span of time between requests_ or by _max requests in span of time_. I think it would be difficult to try to perfectly handle all scenarios, but something approximative can still be very useful.

A `# @wait ???` could be used for each request to indicate the number of ms to wait before [re]executing the request.

A slightly better version IMO could be `# @interval ???` which would wait just long enough to make sure ??? ms have passed since the last executed request (ex: if this is the first request, it doesn't wait at all, if the last request was executed 2s ago, it waits only `??? - 2s`, which may be 0).

Maybe this is enough to handle most use cases (although it might be a bit wasteful in _max requests in span of time_ scenarios, they can still be addressed). It would certainly be enough to take care of my own.

**Comment by AnWeber** [comment]
I have taken the liberty to add the HTTP status code, because third parties will search for it.
In principle, this simple behavior can be easily supplemented yourself. Simply create a NodeJS script with the following content.
```
{{
  exports.waitPromise = new Promise(resolve => setTimeout(resolve, 10000));
}}
```
With this in mind, it would also be possible to integrate a better rate limiter that also implements the correct requirements.
I would like to keep this enhancement as an improvement, but prefer to focus on the other issues at the moment

**Comment by AnWeber** [comment]
currently only added meta option sleep, because I can use this method for my own use case.

**Comment by AnWeber** [comment]
I have added a simple variant of a rate limiter. This can limit the duration between 2 calls (minIdleTime) and the maximum number of requests in a time span. The limitation does not apply per url, but a freely definable slot can be specified.
See https://httpyac.github.io/guide/metaData.html#ratelimit for examples
