### ISSUE TITLE
Allow for variable use in $pick picklists

### ISSUE THREAD

**Issue by jrussellsmyth** [AnWeber/httpyac#537]
It would be very useful if results of a previous query, exported as an array, could be used in a $pick variable assignment

@pick={{$pick select value? $value: $choices}}

where "choices" is a global set by a previous query.

**Comment by AnWeber** [comment]
Currently there is a workaround how you can solve it using Javascript. Just use the UserInteractionProvider directly.

```
{{
  const httpyac = require("httpyac");
  const data = ['foo', 'bar'];

  exports.pick = httpyac.io.userInteractionProvider.showListPrompt("Hello?", data);
}}

GET https://httpbin.org/anything?q={{pick}}
```

I don't like the way that I have to parse double handlebars (`{{$pick select app? $value: {{data}}}}`). Probably I will implement it therefore in such a way that if the string contains no comma, I interpret this as Javascript and with an array as result that then use, otherwise like that on the string fall back (`{{$pick select app? $value: data}}`).

**Comment by AnWeber** [comment]
With next release this example works
```
{{
  exports.data = ["foo", "bar"];
}}
@pick={{ $pick ask-variable? $value: data }}
GET https://httpbin.org/anything?q={{pick}}
```

**Comment by jrussellsmyth** [comment]
Thank you for both the workaround (I will use next business day!) And the
upcoming change which should work perfectly for my use!

**Comment by AnWeber** [comment]
@jrussellsmyth I released the Change Yesterday. There we're other issue I wanted to resolve
