### ISSUE TITLE
AMQP consume does not show the current result as cell output

### ISSUE THREAD

**Issue by patrickhuy** [AnWeber/httpyac#565]
When consuming from AMQP via http book it appears that it shows the previous results instead of the current ones

```
# @keepStreaming

AMQP amqp://guest:guest@localhost
amqp_method: consume
amqp_queue: httpyac_queue
amqp_no_ack: true
###
AMQP amqp://guest:guest@localhost
amqp_method: publish
amqp_exchange: translation.response
amqp_routing_key: httpyac_queue
amqp_replyTo: httpyac_queue
amqp_queue httpyac_queue

something
###
AMQP amqp://guest:guest@localhost
amqp_method: publish
amqp_exchange: translation.response
amqp_routing_key: httpyac_queue
amqp_replyTo: httpyac_queue
amqp_queue httpyac_queue

something else
````

1. Run Consume
2. Run Publish
3. Consume will exit when publish is invoked and show no result (why does it exit? should it not keep streaming? Should i make a seperate issue about this?)
4. Run Consume again. Upon starting consume it will show "something"

When running from httpyac extension the issue also occurs.

**Comment by AnWeber** [comment]
I use a reuse of the AMQP client, but it is buggy. The reason is that on the second call, the first client dropped as a session is not found. However, when storing the session for a second client, the identical ID is used and the first client is closed. 
In discussion AnWeber/vscode-httpyac#231 a generic solution for all clients is described and use this ticket to create the generic logic.
All clients (grpc, amqp, sse, weboscket, http) stores a disconnect Method in sessionStore. This allows cancelation of connection, if session is removed from store. Amqp and Websocket also reuses previous client to alllow feature like ack/nack with the client.
