### ISSUE TITLE
How to read file as request param?

### ISSUE THREAD

**Issue by haxung** [AnWeber/httpyac#601]
Hi, I use `httpyac` as vscode plugin. It's great that support `http`, `grpc` and other requests.
Sometimes param in request is too large, and I hope to read file as param, for example:

```http request
POST http://localhost:8080/upload
Content-Type: application/json

{
  "name": "test",
  "value": "@file//./test"  // the value is too large and save in `test` file.
}
```
This is a wrong case. Does `httpyac` support this function?
Another thing, looks like `httpyac` cannot format `.http` or `.rest` file.

**Comment by AnWeber** [comment]
You can import external [files using this notation.](https://httpyac.github.io/guide/request.html#imported-request-body)

```
POST https://httpbin.org/anything
Content-Type: application/json

< ./requestBodyImport.json
```

And unfortunately I simply don't have the time to implement a formatter. I had planned to do this at some point, but it's not easy to implement due to the different request bodies.

**Comment by haxung** [comment]
I see this case, it means I must save a request body in file, not a param value.
OK, It sounds not bad. Thank you for your help.
