### ISSUE TITLE
Custom HTTP methods

### ISSUE THREAD

**Issue by sdasda7777** [AnWeber/httpyac#632]
Hi, I'm aware this likely won't be easy to do, but could you maybe look into implementing possibility to use custom HTTP methods?

It seems that the HTTP standard, while discouraging it, does in fact allow using custom methods ([according to comments at StackExchange](https://softwareengineering.stackexchange.com/questions/193821/are-there-any-problems-with-implementing-custom-http-methods )), and other similar software seems to allow sending requests with custom HTTP methods as well, such as [Postman](https://blog.postman.com/custom-http-methods-more-flexibility-and-autonomy/) or cURL (using `-X <method>` or `--request <method>`).

**Comment by AnWeber** [comment]
Completely unknown Custom Http Methods would be difficult to implement. I have no mandatory separator between two Http regions (using `###` is optional). I cannot clearly parse whether a new Http region has already been started. In addition, there could be misinterpretations if only one url is used (unfortunately also possible due to compatibility with vscode-restclient). In other words, the Http method should be specified explicitly. However, you could enable custom methods on your own with a custom plugin.

> .httpyac.config.cjs
```js
// support FOO https://httpbin.org/anything
module.exports = {
  configureHooks: function (api) {
    const parseFooMethodRequestLine = api.utils.parseRequestLineFactory({
      protocol: 'HTTP', // enable some http specific hooks, like Cookie support
      methodRegex:
        /^\s*(?<method>FOO)\s+(?<url>.+?)$/u, // regex to parse method and url
      requestClientFactory(request, context) { 
        // create request client used for accessing method/protocol, I use default httpClient
        if (api.httpClientProvider.createRequestClient) {
          return api.httpClientProvider.createRequestClient(request, context);
        }
        throw new Error('Missing Http Client Provider');
      },
      sessionStore: api.sessionStore, // needed for sharing created connection (used for example in grpc, not needed with Http)
    });
    api.hooks.parse.addHook('foo_method', parseFooMethodRequestLine, {
      before: ["request"]
    });
  }
```

**Comment by sdasda7777** [comment]
Whoa, neat, thank you so much!
