### ISSUE TITLE
Variable names are not replaced with their values when displayed on the screen

### ISSUE THREAD

**Issue by rabestro** [AnWeber/httpyac#663]
Problems were discovered with parameterized tests:
- [x] it is impossible to set a dynamic title (only using console.info)
- [x] Variable names are not replaced with their values when displayed on the screen
- [x] the number of requests is counted incorrectly

Test Script: 
https://github.com/rabestro/az204-exercism-functions/blob/main/test-armstrong-numbers.http

```text
---------------------

GET https://jc-exercism.azurewebsites.net/api/armstrong-numbers?number=0
=> 200 (2831 ms, 126 B)
Zero is Armstrong numbers
✓ status == 200
✓ isArmstrongNumber == {{expected}}

---------------------

GET https://jc-exercism.azurewebsites.net/api/armstrong-numbers?number=5
=> 200 (89 ms, 147 B)
Single digits are Armstrong numbers
✓ status == 200
✓ isArmstrongNumber == {{expected}}

---------------------

GET https://jc-exercism.azurewebsites.net/api/armstrong-numbers?number=10
=> 200 (67 ms, 191 B)
There are no two digit Armstrong numbers
✓ status == 200
✓ isArmstrongNumber == {{expected}}

---------------------

GET https://jc-exercism.azurewebsites.net/api/armstrong-numbers?number=9926315
=> 200 (68 ms, 190 B)
A seven digit number that is an Armstrong number
✓ status == 200
✓ isArmstrongNumber == {{expected}}

---------------------

GET https://jc-exercism.azurewebsites.net/api/armstrong-numbers?number=9926314
=> 200 (66 ms, 191 B)
A seven digit number that is not an Armstrong number
✓ status == 200
✓ isArmstrongNumber == {{expected}}

---------------------

GET https://jc-exercism.azurewebsites.net/api/armstrong-numbers
=> 400 (74 ms, 218 B)
✓ status == 400
✓ message exists
✓ message == Please pass a number on the query string

7 requests processed (7 succeeded, 0 failed)
```

**Comment by AnWeber** [comment]
I'm with you on points 2 and 3 and I'll adjust it straight away. I don't currently have dynamic titles and I can't implement them cleanly at the moment, because in some places where I use the title, I no longer have access to the variable replacement. It is also not possible to carry out the replacement right at the start of the region, as the required variables are not available. 
A hacky way would be to set the title yourself, but you have to keep in mind that the title may remain, since the httpRegion represents the object from the parsing and should not actually be changed.

```
{{
    httpRegion.metaData.title = description
    console.info(description);
}}
```

**Comment by rabestro** [comment]
> httpRegion.metaData.title = description

It works for me! Will it be represented in JUnit XML reports as well?

**Comment by AnWeber** [comment]
yes
