### ISSUE TITLE
CLI Options documentation clarification

### ISSUE THREAD

**Issue by mmadson** [AnWeber/httpyac#705]
Howdy @AnWeber 

Happy Friday! Few questions for you. 

For the `--timeout` option, is this specified in milliseconds or seconds and does it affect the connection timeout / request timeout or both? Perhaps we should support finer granularity here so that we can specify a max connection timeout separately from a max request timeout?

For the `--repeat` option is this simply a count for how many times each http request should be run or is this a retry mechanism for failed tests? If it's the former, perhaps we should add a new feature `--retry` which is specifically for retrying failed tests. 

Finally I have a question about `--bail`. One of our recent test runs encountered an ECONNFESUED failure emitted from httpyac. I believe the server that we were testing was refusing connections but I was surprised that this resulted in a runtime failure for httpyac without the bail flag specified. My expectation is that tiemout or connection errors during a test case run would simply be reported in the test output as a kind of test failure -- but would not interrupt the test suite execution. 

Thoughts?

Thanks as always for your consideration.

**Comment by AnWeber** [comment]
> For the --repeat option is this simply a count for how many times each http request should be run

Yes, exactly. This argument dates back to the early days, when I didn't see it being used as a test tool. I simply wanted to be able to put my server under load so that I could trigger a race condition. Offering a retry for the tests may make sense, as you always have flaky tests (new issue?)

> For the --timeout option, is this specified in milliseconds or seconds and does it affect the connection timeout / request timeout or both?

Timeout in milliseconds. It is used as timeout param for Http Requests (got), Websocket Request, GRPC Requests and Mqtt Requests. Your use case should be http. Got docs mention this for the timeout property:  Milliseconds to wait for the server to end the response before aborting the request with `got.TimeoutError` error (a.k.a. `request` property).
    By default, there's no timeout.. But it also supports a extended timeout object (see [docs](https://github.com/sindresorhus/got/blob/HEAD/documentation/6-timeout.md)). Only http calls will support this object

> Finally I have a question about --bail ... My expectation is that tiemout or connection errors during a test case run would simply be reported in the test output as a kind of test failure

I agree. In my usage, it can actually always abort immediately in this case because I only test one endpoint, but this kind of error handling makes sense. `--bail` is meant to abort immediately on test failure. But the behavior is simply because I forgot to put the execution in a try/catch and did not handle this error correctly.

**Comment by mmadson** [comment]
Thanks for the clarifications. I've gone ahead and created #707 and #708. Feel free to consider this issue / discussion closed and of course if you need a hand, just let me know.
