### ISSUE TITLE
Bug Report: uncaught ECONNREFUSED errors causing runtime errors without bail flag

### ISSUE THREAD

**Issue by mmadson** [AnWeber/httpyac#708]
Continued from discussion in #705

Expected: if server refuses an http connection for an httpyac client request, the http region / test should be reported as a failure in the test report / output but should continue on to execute the next http region / test until all tests have been executed -- unless of course the --bail cli flag is provided in which case, propagating the error and terminating the test suite early is the desired behavior.

Actual: if server refuses an http connection for an httpyac client request, test execution terminates early and the ECONNREFUSED error is propagated regardless of whether the bail flag is supplied or not.

**Comment by AnWeber** [comment]
I have now restructured it once so that the exceptions only affect the respective httpRegion. This means that I had to revise the handling for ExitCode and bail. I should have tested everything thoroughly, but this could still lead to unexpected conflicts. But I agree with you that the behavior for tests is not optimal and that your desired behavior should be implemented here. I will release it with the next release
