### ISSUE TITLE
Variables shared across files

### ISSUE THREAD

**Issue by jhonnycano** [AnWeber/httpyac#73]
I wonder if there is something that supports a flow like the following:

## FILE A

```
POST /endpoint/auth

{ "user": "user", "password": "password" }


{{
	// post-request
	httpyac.globals.set('token', response.parsedBody.token);
}}
```

## FILE B

```
{{
	// pre-request
	exports.token = httpyac.globals.get('token');
}}

POST /endpoint/action-1
Authorization: Bearer {{token}}

{ "hello": "world" }
```

I tried using ```httpFile.variablesPerEnv``` but this collection only stores the variables for the current file, not for the whole environment. 
Keep up the good work, thanks!

**Comment by AnWeber** [comment]
For this purpose I have included [@import](https://httpyac.github.io/guide/metaData.html#import) and [@ref](https://httpyac.github.io/guide/metaData.html#ref-and-forceref). The combination allows together, the outsourcing of own authentication requests.

[importGlobal.http](https://github.com/httpyac/httpyac.github.io/blob/main/examples/metaData/importGlobal.http)
```
# @import ./name.http

###
# @ref auth
POST https://httpbin.org/anything HTTP/1.1
{{auth.slideshow.author}}
```
[name.http](https://github.com/httpyac/httpyac.github.io/blob/main/examples/metaData/name.http)
```
# @name auth
GET https://httpbin.org/json HTTP/1.1
```
Alternative would be to use an [Intellij Script](https://github.com/httpyac/httpyac.github.io/blob/main/examples/script/intellij.http), because there the variables are stored [globally](https://github.com/AnWeber/httpyac/blob/main/src/variables/provider/intellijGlobalVariableProvider.ts#L4). But the order of the calls must be ensured by yourself.
```
POST /auth HTTP/1.1
Content-Type: application/x-www-form-urlencode

email=user@domain.loc&password=3

> {% client.global.set("email", response.body.form.email); %}
```

**Comment by AnWeber** [comment]
Just leave a comment, if you need more help. Thx.
