### ISSUE TITLE
Failing to receive auth token w/ oauth2 client credentials flow results in exit code 0

### ISSUE THREAD

**Issue by tyler-hagen** [AnWeber/httpyac#760]
I have some tests running in a pipeline, and ended up configuring and invalid client_id/client_secret. This resulted in a 401 response from the auth server, which I can see in the logs.

I expected the behavior to be that all my tests that reference the prefix with the invalid client_id and client_secret would be failed tests, and therefore the process would exit with some sort of error code that my pipeline runner could recognize as a failure. Because the behavior is to just essentially skip the test and not count it as a pass or fail, and exit successfully, I was not able to recognize my tests were not being run for some time.

I'm not sure if this is actually an issue or if I'm misusing the tool. Any suggestions?

**Comment by AnWeber** [comment]
Hi, the behavior is indeed not good. I have adjusted it and generate an error status in this case as well. The case did not throw an exception and was simply canceled directly and therefore generated the skipped status. Since I have revised the procedure as part of another ticket, I will include your issue there directly. It should be fixed with the next release.

**Comment by tyler-hagen** [comment]
Thank you @AnWeber ! Please let me know if I can help in any way.
