### ISSUE TITLE
AWS SigV4 invalid signature, lacking date header

### ISSUE THREAD

**Issue by LaurenceGA** [AnWeber/httpyac#769]
Everything has been working fine signing AWS SigV4 requests.

I came back to the same requests after a bit and am getting a 403 with message

```
{
  "message": "Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. ..."
}
```

It also has `SignedHeaders=accept;caller-account-id;host;x-amz-date;x-amz-security-token`

Seems something odd is going on with the signing.

I tried manually adding a `X-Amz-Date` header as a workaround, but then it just says `The security token included in the request is invalid.`

Not sure what changed, but I haven't updated my requests, so it's maybe either httpyac (I'm testing with CLI) or AWS.

Any help would be appreciated. This has completely broken all of my Sigv4 signed requests.

**Comment by AnWeber** [comment]
sorry. There was a Breaking Change in in the behaviour of the lib I use to get aws header. Unfortunately, it was only marked as a feature release and I had overlooked it. Now the headers are no longer changed but copied beforehand. Now I have to make the header changes myself. It will be fixed with next release

https://github.com/mhart/aws4/releases/tag/v1.13.0
